#! /usr/bin/perl

use strict;
use warnings;

use Cwd qw/abs_path/;
use File::Basename qw/dirname/;
use File::Spec;

use feature qw/say/;
use Honeydew::ExternalServices::Crontab qw/add_crontab_section/;

say $_ for @{ update_crontab() };

sub get_bmp_crontab_entry {
    my $relative_restart = 'bmp-restart';
    my $restart_bmp = File::Spec->catfile(
        abs_path(dirname(__FILE__)),
        $relative_restart
    );

    my $bmp_crontab_entry = qq%# restart the browsermob process if needed
*/5 * * * * if [ \$(ps aux | grep [j]ava.*bmp | wc -l) -eq '0' ]; then $restart_bmp ; fi

# force a restart every night before the nightlies
55 19 * * * $restart_bmp
%;

    return [ split("\n", $bmp_crontab_entry) ];
}

sub update_crontab {
    return add_crontab_section( 'browsermob', get_bmp_crontab_entry() );
}
